services:
  portarias:
    image: portarias:latest
    container_name: portarias
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    networks:
      - portarias-network
    volumes:
      - ./:/var/www/html
    environment:
      HOME: /tmp
    user: "${UID:-1000}:${GID:-1000}"

  mariadb:
    image: mariadb:11
    container_name: portarias_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: portarias
      MYSQL_USER: portarias
      MYSQL_PASSWORD: portarias
      MYSQL_ROOT_PASSWORD: portarias
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - portarias-network

  selenium:
    image: selenium/standalone-chrome
    container_name: portarias_selenium
    ports:
      - "7900:7900" # VNC (pra ver o browser rodando)
    networks:
      - portarias-network
    shm_size: 2gb
    
  senhaunica-faker:
    image: uspdev/senhaunica-faker
    container_name: portarias_senhaunica-faker
    ports:
      - "3141:3141"
    environment:
          - APP_URL=http://auth.local:3141
    networks:
      portarias-network:
        aliases:
          - auth.local

networks:
  portarias-network:

volumes:
  mariadb_data: